services:
  grafana:
    user: root
    container_name: 'fci-reactflow-app'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/fci-reactflow-app
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/fci-reactflow-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.fci-reactflow-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: fci-reactflow-app
